/* StatHub: client-side statistics workspace.
   Add Supabase URL and publishable/anon key below to enable authentication and cloud saves.
   Never put a Supabase service_role key in browser code. */
const SUPABASE_URL = "https://vslkfqdcevyiehdvkkme.supabase.co"; // e.g. https://YOUR_PROJECT.supabase.co
const SUPABASE_ANON_KEY = "sb_publishable_3-MNRr_KjxFvC0uRdoJpCg_vp9wTAvB"; // Supabase publishable/anon key
const supabaseReady = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY && window.supabase);
const db = supabaseReady ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const view = $("#view");
let currentModule = "home";
let authMode = "signin";
let currentUser = null;
let latestAnalysis = null;

const modules = {
  descriptive:{title:"Descriptive Statistics",subtitle:"Summarize, understand, and visualize the shape of your data.",icon:"▥",desc:"Calculate measures of center and spread, then inspect your distribution.",button:"Analyze data"},
  probability:{title:"Probability",subtitle:"Explore random variables, discrete distributions, and event probabilities.",icon:"⚄",desc:"Calculate binomial probabilities and visualize a probability mass function.",button:"Calculate probability"},
  sampling:{title:"Sampling Distributions",subtitle:"Explore sample means and the Central Limit Theorem through simulation.",icon:"∿",desc:"Generate repeated samples and observe how sample means behave.",button:"Run simulation"},
  inference:{title:"Inferential Statistics",subtitle:"Use sample evidence to estimate population parameters and test hypotheses.",icon:"𝑡",desc:"Run a one-sample t-test and confidence interval for a population mean.",button:"Run t-test"},
  regression:{title:"Regression Analysis",subtitle:"Measure relationships and fit a simple least-squares regression model.",icon:"↗",desc:"Estimate a regression line, correlation, R², and fitted values.",button:"Run regression"},
  demography:{title:"Demography",subtitle:"Explore population structure, growth, and key demographic indicators.",icon:"♧",desc:"Calculate growth rates and dependency ratios from population counts.",button:"Analyze population"}
};
const sampleData = "22, 16, 5\n25, 17, 6\n28, 17, 7\n31, 16, 6\n24, 16, 5\n27, 18, 7\n26, 17, 6\n23, 15, 5";

function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function num(v){return Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:4}):"—";}
function parseNumbers(text){const values=text.trim().split(/[\s,;\t]+/).filter(Boolean).map(Number);if(!values.length||values.some(v=>!Number.isFinite(v)))throw Error("Enter numeric values separated by commas, spaces, or new lines.");return values;}
function mean(a){return a.reduce((s,v)=>s+v,0)/a.length;}
function variance(a,sample=true){if(a.length<(sample?2:1))return NaN;const m=mean(a);return a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-(sample?1:0));}
function quantile(a,q){const x=[...a].sort((u,v)=>u-v),p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i+1]===undefined?x[i]:x[i]+f*(x[i+1]-x[i]);}
function median(a){return quantile(a,.5);}
function modeOf(a){const counts=new Map();a.forEach(v=>counts.set(v,(counts.get(v)||0)+1));const max=Math.max(...counts.values());if(max===1)return "No repeated value";return [...counts].filter(x=>x[1]===max).map(x=>x[0]).join(", ");}
function std(a,sample=true){return Math.sqrt(variance(a,sample));}
function sum(a){return a.reduce((s,v)=>s+v,0);}
function factorial(n){let r=1;for(let i=2;i<=n;i++)r*=i;return r;}
function choose(n,k){if(k<0||k>n)return 0;k=Math.min(k,n-k);let r=1;for(let i=1;i<=k;i++)r=r*(n-k+i)/i;return r;}
function binomPmf(n,k,p){return choose(n,k)*p**k*(1-p)**(n-k);}
function erf(x){const sign=x<0?-1:1;x=Math.abs(x);const t=1/(1+.3275911*x);const y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x);return sign*y;}
function normalCdf(z){return .5*(1+erf(z/Math.sqrt(2)));}
function logGamma(z){const p=[676.5203681218851,-1259.1392167224028,771.3234287776531,-176.61502916214059,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z-=1;let x=.99999999999980993;p.forEach((v,i)=>x+=v/(z+i+1));const t=z+p.length-.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x);}
function betaCF(a,b,x){const max=200,eps=3e-12,fpmin=1e-30;let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<fpmin)d=fpmin;d=1/d;let h=d;for(let m=1;m<=max;m++){let m2=2*m,aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<fpmin)d=fpmin;c=1+aa/c;if(Math.abs(c)<fpmin)c=fpmin;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<fpmin)d=fpmin;c=1+aa/c;if(Math.abs(c)<fpmin)c=fpmin;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<eps)break;}return h;}
function regBeta(x,a,b){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaCF(a,b,x)/a:1-bt*betaCF(b,a,1-x)/b;}
function tCdf(t,df){const x=df/(df+t*t),ib=regBeta(x,df/2,.5);return t>=0?1-.5*ib:.5*ib;}
function tCriticalApprox(df,confidence=.95){ // numerical inversion of Student t CDF
 const target=(1+confidence)/2;let lo=0,hi=20;for(let i=0;i<80;i++){const mid=(lo+hi)/2;if(tCdf(mid,df)<target)lo=mid;else hi=mid;}return (lo+hi)/2;
}
function corr(x,y){const mx=mean(x),my=mean(y);let n=0,d1=0,d2=0;for(let i=0;i<x.length;i++){n+=(x[i]-mx)*(y[i]-my);d1+=(x[i]-mx)**2;d2+=(y[i]-my)**2;}return n/Math.sqrt(d1*d2);}
function chart(id,traces,layout={}){if(!window.Plotly){$(id)?.replaceChildren(document.createTextNode("Chart library could not load. Check your internet connection."));return;}const el=$(id);if(!el)return;Plotly.newPlot(el,traces,{margin:{l:48,r:18,t:16,b:45},paper_bgcolor:"#fff",plot_bgcolor:"#fff",font:{family:"Inter, system-ui, sans-serif",color:"#617b93",size:11},xaxis:{gridcolor:"#edf3f8",zerolinecolor:"#dce8f2"},yaxis:{gridcolor:"#edf3f8",zerolinecolor:"#dce8f2"},...layout},{responsive:true,displaylogo:false});}
function metric(label,value,sub=""){return `<div class="result-item"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:""}</div>`;}
function moduleHeader(key){const m=modules[key];return `<div class="page-header"><div><div class="eyebrow">STATISTICS MODULE</div><h1>${m.icon} ${m.title}</h1><p>${m.subtitle}</p></div><span class="pill"><span class="status-dot"></span> Interactive workspace</span></div>`;}
function panel(title,body,extra=""){return `<section class="panel ${extra}"><div class="panel-head"><h2>${title}</h2></div><div class="panel-body">${body}</div></section>`;}
function renderHome(){
 view.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">WELCOME TO YOUR WORKSPACE</div><h1>Make data make <em>sense.</em></h1><p>Explore statistical concepts, analyze your own datasets, and turn calculations into clear visual insights — all in one place.</p><button class="button button-primary" data-go="descriptive">Start analyzing <span>→</span></button></div><div class="hero-art" aria-hidden="true">▥</div></section>
 <div class="section-heading"><div><h2>Explore modules</h2><p>Tools designed for university statistics students.</p></div></div>
 <div class="module-grid">${Object.entries(modules).map(([key,m])=>`<article class="module-card"><div class="module-top"><div class="module-icon">${m.icon}</div><h3>${m.title}</h3></div><p>${m.desc}</p><button class="button" data-go="${key}">Open module →</button></article>`).join("")}</div>
 <div class="stats-row"><div class="stat-tile"><span class="label">Learning modules</span><strong>06</strong><small>Core statistics topics</small></div><div class="stat-tile"><span class="label">Visualization engine</span><strong>Plotly</strong><small>Interactive charts</small></div><div class="stat-tile"><span class="label">Workspace mode</span><strong>${currentUser?"Cloud-ready":"Guest"}</strong><small>${currentUser?"Signed in":"No account required"}</small></div></div>`;
}
function renderDescriptive(){
 view.innerHTML=moduleHeader("descriptive")+`<div class="workspace-grid">${panel("Data input",`<div class="form-stack"><div class="field"><label for="descData">Numeric dataset</label><textarea id="descData">${sampleData}</textarea><span class="help">Paste numbers separated by commas, spaces, tabs, or new lines.</span></div><div class="inline-fields"><div class="field"><label for="descSample">Variance / SD type</label><select id="descSample"><option value="sample">Sample (n − 1)</option><option value="population">Population (n)</option></select></div><div class="field"><label for="descTitle">Chart label</label><input id="descTitle" value="Data distribution"></div></div><button id="runDesc" class="button button-primary">${modules.descriptive.button} →</button><div id="descError" class="message"></div></div>`)}${panel("Summary output",`<div id="descMetrics" class="result-grid"></div><div class="table-wrap"><table id="descTable"></table></div>`)} </div>${panel("Distribution visualization",`<div id="descChart" class="chart"></div>`,"chart-panel")}<div class="section-heading"><div><h2>Save your analysis</h2><p>Save the current input and summary to your workspace.</p></div><button id="saveAnalysis" class="button button-light">Save result</button></div><div id="saveMessage" class="message"></div>`;
 $("#runDesc").onclick=runDescriptive;$("#saveAnalysis").onclick=()=>saveCurrent("Descriptive Statistics");runDescriptive();
}
function runDescriptive(){
 try{const a=parseNumbers($("#descData").value),sample=$("#descSample").value==="sample",m=mean(a),v=variance(a,sample),sd=Math.sqrt(v),sorted=[...a].sort((x,y)=>x-y),min=sorted[0],max=sorted.at(-1);const data=[["Count",a.length],["Mean",m],["Median",median(a)],["Mode",modeOf(a)],["Variance",v],["Standard deviation",sd],["Minimum",min],["Q1",quantile(a,.25)],["Q3",quantile(a,.75)],["Maximum",max],["Range",max-min],["IQR",quantile(a,.75)-quantile(a,.25)]];$("#descMetrics").innerHTML=[metric("Observations",num(a.length)),metric("Mean",num(m)),metric("Median",num(median(a))),metric("Std. deviation",num(sd))].join("");$("#descTable").innerHTML=`<thead><tr><th>Measure</th><th>Value</th></tr></thead><tbody>${data.map(r=>`<tr><td>${r[0]}</td><td>${num(r[1])}</td></tr>`).join("")}</tbody>`;const minBin=Math.min(...a),maxBin=Math.max(...a),bins=Math.min(20,Math.max(5,Math.ceil(Math.sqrt(a.length))));chart("#descChart",[{x:a,type:"histogram",nbinsx:bins,marker:{color:"#2999ef",line:{color:"#fff",width:1}},opacity:.9,name:"Frequency"}],{title:{text:$("#descTitle").value||"Data distribution",font:{size:13,color:"#173452"}},xaxis:{title:"Value"},yaxis:{title:"Frequency"}});latestAnalysis={module:"Descriptive Statistics",input:$("#descData").value,results:Object.fromEntries(data)};$("#descError").textContent="";}catch(e){$("#descError").textContent=e.message;}
}
function renderProbability(){
 view.innerHTML=moduleHeader("probability")+`<div class="workspace-grid">${panel("Binomial distribution",`<div class="form-stack"><div class="notice">Use this model when there are a fixed number of independent trials, each with the same probability of success.</div><div class="inline-fields"><div class="field"><label for="binN">Trials (n)</label><input id="binN" type="number" min="1" max="500" value="10"></div><div class="field"><label for="binP">Success probability (p)</label><input id="binP" type="number" min="0" max="1" step=".01" value=".3"></div></div><div class="field"><label for="binK">Success count (x)</label><input id="binK" type="number" min="0" value="3"></div><div class="field"><label for="binEvent">Probability event</label><select id="binEvent"><option value="eq">P(X = x)</option><option value="le">P(X ≤ x)</option><option value="ge">P(X ≥ x)</option></select></div><button id="runBin" class="button button-primary">Calculate probability →</button><div id="binError" class="message"></div></div>`)}${panel("Probability result",`<div id="binMetrics" class="result-grid"></div><div id="binInterpretation" class="notice" style="margin-top:12px"></div>`)}</div>${panel("Binomial probability mass function",`<div id="binChart" class="chart"></div>`,"chart-panel")}`;
 $("#runBin").onclick=runBinomial;runBinomial();
}
function runBinomial(){try{const n=Number($("#binN").value),p=Number($("#binP").value),k=Number($("#binK").value),event=$("#binEvent").value;if(!Number.isInteger(n)||n<1||n>500||p<0||p>1||!Number.isInteger(k)||k<0||k>n)throw Error("Use integer n (1–500), p between 0 and 1, and x between 0 and n.");const probs=Array.from({length:n+1},(_,i)=>binomPmf(n,i,p));let result=event==="eq"?probs[k]:event==="le"?sum(probs.slice(0,k+1)):sum(probs.slice(k));$("#binMetrics").innerHTML=[metric("Requested probability",num(result)),metric("Expected value E(X)",num(n*p)),metric("Variance",num(n*p*(1-p))),metric("Standard deviation",num(Math.sqrt(n*p*(1-p))))].join("");$("#binInterpretation").textContent=`The requested event has probability ${num(result)} (${num(result*100)}%).`;chart("#binChart",[{x:Array.from({length:n+1},(_,i)=>i),y:probs,type:"bar",marker:{color:"#238fe7"},name:"P(X = x)"}],{xaxis:{title:"Number of successes (x)",dtick:n<=30?1:undefined},yaxis:{title:"Probability"}});$("#binError").textContent="";latestAnalysis={module:"Probability",input:{n,p,k,event},results:{probability:result,expected:n*p,variance:n*p*(1-p)}};}catch(e){$("#binError").textContent=e.message;}}
function renderSampling(){
 view.innerHTML=moduleHeader("sampling")+`<div class="workspace-grid">${panel("Simulation settings",`<div class="form-stack"><div class="notice">Repeatedly draw samples from a population, then chart the sample means. Simulation results vary slightly each run.</div><div class="inline-fields"><div class="field"><label for="sampN">Sample size (n)</label><input id="sampN" type="number" min="2" max="500" value="30"></div><div class="field"><label for="sampR">Repetitions</label><input id="sampR" type="number" min="100" max="10000" step="100" value="1000"></div></div><div class="inline-fields"><div class="field"><label for="popMean">Population mean</label><input id="popMean" type="number" value="20"></div><div class="field"><label for="popSd">Population SD</label><input id="popSd" type="number" min=".01" value="5"></div></div><button id="runSamp" class="button button-primary">Run simulation →</button><div id="sampError" class="message"></div></div>`)}${panel("Simulation summary",`<div id="sampMetrics" class="result-grid"></div><div class="notice" style="margin-top:12px">The standard error of the sample mean is approximately σ / √n. This simulation assumes a normal population.</div>`)}</div>${panel("Distribution of sample means",`<div id="sampChart" class="chart"></div>`,"chart-panel")}`;
 $("#runSamp").onclick=runSampling;runSampling();
}
function randn(){let u=0,v=0;while(u===0)u=Math.random();while(v===0)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function runSampling(){try{const n=Number($("#sampN").value),r=Number($("#sampR").value),mu=Number($("#popMean").value),sigma=Number($("#popSd").value);if(!Number.isInteger(n)||n<2||n>500||!Number.isInteger(r)||r<100||r>10000||sigma<=0)throw Error("Use n = 2–500, repetitions = 100–10,000, and SD > 0.");const means=Array.from({length:r},()=>{let s=0;for(let j=0;j<n;j++)s+=mu+sigma*randn();return s/n;});const m=mean(means),sd=std(means);$("#sampMetrics").innerHTML=[metric("Simulated samples",num(r)),metric("Mean of sample means",num(m)),metric("Simulated standard error",num(sd)),metric("Theoretical SE",num(sigma/Math.sqrt(n)))].join("");chart("#sampChart",[{x:means,type:"histogram",nbinsx:35,marker:{color:"#218de4"},name:"Sample means"}],{xaxis:{title:"Sample mean"},yaxis:{title:"Frequency"},shapes:[{type:"line",x0:mu,x1:mu,y0:0,y1:1,yref:"paper",line:{color:"#e36c5b",dash:"dash",width:2}}]});$("#sampError").textContent="";latestAnalysis={module:"Sampling Distributions",input:{n,repetitions:r,populationMean:mu,populationSD:sigma},results:{meanOfMeans:m,simulatedSE:sd,theoreticalSE:sigma/Math.sqrt(n)}};}catch(e){$("#sampError").textContent=e.message;}}
function renderInference(){
 view.innerHTML=moduleHeader("inference")+`<div class="workspace-grid">${panel("One-sample t-test",`<div class="form-stack"><div class="notice">Tests H₀: μ = μ₀ using a one-sample t statistic. The two-sided p-value uses the Student t distribution.</div><div class="field"><label for="infData">Sample values</label><textarea id="infData">${"12, 14, 13, 15, 11, 16, 14, 13, 15, 12"}</textarea></div><div class="inline-fields"><div class="field"><label for="infMu">Hypothesized mean (μ₀)</label><input id="infMu" type="number" value="12"></div><div class="field"><label for="infAlpha">Significance level (α)</label><select id="infAlpha"><option value=".10">0.10</option><option value=".05" selected>0.05</option><option value=".01">0.01</option></select></div></div><button id="runInf" class="button button-primary">Run t-test →</button><div id="infError" class="message"></div></div>`)}${panel("Test results",`<div id="infMetrics" class="result-grid"></div><div id="infDecision" class="notice" style="margin-top:12px"></div>`)}</div>${panel("Sample distribution",`<div id="infChart" class="chart"></div>`,"chart-panel")}`;
 $("#runInf").onclick=runInference;runInference();
}
function runInference(){try{const a=parseNumbers($("#infData").value),mu0=Number($("#infMu").value),alpha=Number($("#infAlpha").value);if(a.length<2)throw Error("At least two observations are required.");const m=mean(a),s=std(a),se=s/Math.sqrt(a.length),t=(m-mu0)/se,df=a.length-1,p=2*(1-tCdf(Math.abs(t),df)),crit=tCriticalApprox(df,1-alpha),lo=m-crit*se,hi=m+crit*se,reject=p<alpha;$("#infMetrics").innerHTML=[metric("Sample size",num(a.length)),metric("t statistic",num(t)),metric("Degrees of freedom",num(df)),metric("Two-sided p-value",num(p)),metric(`${num(1-alpha)} confidence interval`,`${num(lo)} to ${num(hi)}`),metric("Sample mean",num(m))].join("");$("#infDecision").textContent=`${reject?"Reject":"Fail to reject"} H₀ at α = ${alpha}. ${reject?"The sample provides evidence that the population mean differs from "+mu0+".":"The sample does not provide sufficient evidence that the population mean differs from "+mu0+"."} This conclusion depends on the sampling assumptions.`;chart("#infChart",[{x:a,type:"histogram",nbinsx:Math.min(15,Math.ceil(Math.sqrt(a.length))),marker:{color:"#218de4"},name:"Sample"}],{xaxis:{title:"Observed value"},yaxis:{title:"Frequency"}});$("#infError").textContent="";latestAnalysis={module:"Inferential Statistics",input:{sample:a,hypothesizedMean:mu0,alpha},results:{n:a.length,mean:m,sd:s,t,df,p,confidenceInterval:[lo,hi],decision:reject?"Reject H0":"Fail to reject H0"}};}catch(e){$("#infError").textContent=e.message;}}
function renderRegression(){
 view.innerHTML=moduleHeader("regression")+`<div class="workspace-grid">${panel("Paired data input",`<div class="form-stack"><div class="field"><label for="regX">X values (independent variable)</label><textarea id="regX">1, 2, 3, 4, 5, 6, 7, 8</textarea></div><div class="field"><label for="regY">Y values (dependent variable)</label><textarea id="regY">35, 39, 43, 48, 50, 58, 61, 65</textarea></div><span class="help">X and Y must contain the same number of numeric observations in matching order.</span><button id="runReg" class="button button-primary">Run regression →</button><div id="regError" class="message"></div></div>`)}${panel("Model summary",`<div id="regMetrics" class="result-grid"></div><div class="table-wrap"><table id="regTable"></table></div>`)}</div>${panel("Scatterplot and fitted line",`<div id="regChart" class="chart"></div>`,"chart-panel")}`;
 $("#runReg").onclick=runRegression;runRegression();
}
function runRegression(){try{const x=parseNumbers($("#regX").value),y=parseNumbers($("#regY").value);if(x.length!==y.length||x.length<3)throw Error("X and Y need the same number of values (at least 3).");const mx=mean(x),my=mean(y);let sxx=0,sxy=0,syy=0;for(let i=0;i<x.length;i++){sxx+=(x[i]-mx)**2;sxy+=(x[i]-mx)*(y[i]-my);syy+=(y[i]-my)**2;}if(sxx===0)throw Error("X values must not all be identical.");const b1=sxy/sxx,b0=my-b1*mx,r=corr(x,y),r2=r*r,fitted=x.map(v=>b0+b1*v),resid=y.map((v,i)=>v-fitted[i]),sse=sum(resid.map(v=>v*v)),se=Math.sqrt(sse/(x.length-2));$("#regMetrics").innerHTML=[metric("Observations",num(x.length)),metric("Intercept (b₀)",num(b0)),metric("Slope (b₁)",num(b1)),metric("Correlation (r)",num(r)),metric("R²",num(r2)),metric("Residual standard error",num(se))].join("");$("#regTable").innerHTML=`<thead><tr><th>Observation</th><th>X</th><th>Observed Y</th><th>Fitted Y</th><th>Residual</th></tr></thead><tbody>${x.map((v,i)=>`<tr><td>${i+1}</td><td>${num(v)}</td><td>${num(y[i])}</td><td>${num(fitted[i])}</td><td>${num(resid[i])}</td></tr>`).join("")}</tbody>`;const xs=[Math.min(...x),Math.max(...x)];chart("#regChart",[{x,y,mode:"markers",type:"scatter",name:"Observed data",marker:{color:"#1688e8",size:9}},{x:xs,y:xs.map(v=>b0+b1*v),mode:"lines",type:"scatter",name:"Fitted line",line:{color:"#ef8354",width:3}}],{xaxis:{title:"X (independent variable)"},yaxis:{title:"Y (dependent variable)"}});$("#regError").textContent="";latestAnalysis={module:"Regression Analysis",input:{x,y},results:{n:x.length,intercept:b0,slope:b1,correlation:r,rSquared:r2,residualStandardError:se}};}catch(e){$("#regError").textContent=e.message;}}
function renderDemography(){
 view.innerHTML=moduleHeader("demography")+`<div class="workspace-grid">${panel("Population data",`<div class="form-stack"><div class="inline-fields"><div class="field"><label for="demoPop">Current population</label><input id="demoPop" type="number" min="0" value="125000"></div><div class="field"><label for="demoPrev">Previous population</label><input id="demoPrev" type="number" min="0" value="120000"></div></div><div class="inline-fields"><div class="field"><label for="demoBirth">Live births per year</label><input id="demoBirth" type="number" min="0" value="2600"></div><div class="field"><label for="demoDeath">Deaths per year</label><input id="demoDeath" type="number" min="0" value="900"></div></div><div class="field"><label for="demoYear">Time interval (years)</label><input id="demoYear" type="number" min=".1" step=".1" value="1"></div><div class="field"><label for="demoAge">Age composition (optional)</label><textarea id="demoAge">Age group,Population\n0-14,28000\n15-64,85000\n65+,12000</textarea><span class="help">Optional CSV: first row header, then age group and population.</span></div><button id="runDemo" class="button button-primary">Analyze population →</button><div id="demoError" class="message"></div></div>`)}${panel("Demographic indicators",`<div id="demoMetrics" class="result-grid"></div><div id="demoTable" class="table-wrap"></div>`)}</div>${panel("Population by age group",`<div id="demoChart" class="chart"></div>`,"chart-panel")}`;
 $("#runDemo").onclick=runDemography;runDemography();
}
function runDemography(){try{const pop=Number($("#demoPop").value),prev=Number($("#demoPrev").value),birth=Number($("#demoBirth").value),death=Number($("#demoDeath").value),years=Number($("#demoYear").value);if(pop<=0||prev<=0||birth<0||death<0||years<=0)throw Error("Population values must be positive; births/deaths cannot be negative; years must be greater than zero.");const growth=(pop/prev)**(1/years)-1,birthRate=birth/pop*1000,deathRate=death/pop*1000,natural=(birth-death)/pop*1000;let rows=[],labels=[],vals=[];const lines=$("#demoAge").value.trim().split(/\n/).slice(1);for(const line of lines){const parts=line.split(",");if(parts.length>=2&&parts[0].trim()&&Number.isFinite(Number(parts[1]))&&Number(parts[1])>=0){labels.push(parts[0].trim());vals.push(Number(parts[1]));rows.push([parts[0].trim(),Number(parts[1])]);}}let dependency="—";const child=rows.find(r=>/0.?14|child/i.test(r[0]))?.[1],working=rows.find(r=>/15.?64|working/i.test(r[0]))?.[1],older=rows.find(r=>/65\+|65.?plus|elder/i.test(r[0]))?.[1];if(working>0&&child!==undefined&&older!==undefined)dependency=(child+older)/working*100;$("#demoMetrics").innerHTML=[metric("Current population",num(pop)),metric("Annualized growth",num(growth*100)+"%"),metric("Crude birth rate",num(birthRate),"per 1,000 population"),metric("Crude death rate",num(deathRate),"per 1,000 population"),metric("Natural increase",num(natural),"per 1,000 population"),metric("Dependency ratio",dependency==="—"?"Add age groups":num(dependency)+"%","0–14 and 65+ / age 15–64")].join("");$("#demoTable").innerHTML=rows.length?`<table><thead><tr><th>Age group</th><th>Population</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${num(r[1])}</td></tr>`).join("")}</tbody></table>`:"";if(rows.length)chart("#demoChart",[{x:labels,y:vals,type:"bar",marker:{color:"#238fe7"}}],{xaxis:{title:"Age group"},yaxis:{title:"Population"}});else chart("#demoChart",[{x:["Previous","Current"],y:[prev,pop],type:"bar",marker:{color:["#9acff5","#1688e8"]}}],{xaxis:{title:"Period"},yaxis:{title:"Population"}});$("#demoError").textContent="";latestAnalysis={module:"Demography",input:{pop,prev,birth,death,years,ageGroups:rows},results:{annualizedGrowthRate:growth,birthRate,deathRate,naturalIncreaseRate:natural,dependencyRatio:dependency}};}catch(e){$("#demoError").textContent=e.message;}}
function renderModule(key){currentModule=key;$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.module===key));if(key==="home")renderHome();else if(key==="descriptive")renderDescriptive();else if(key==="probability")renderProbability();else if(key==="sampling")renderSampling();else if(key==="inference")renderInference();else if(key==="regression")renderRegression();else if(key==="demography")renderDemography();window.scrollTo({top:0,behavior:"smooth"});}
$$(".nav-item").forEach(b=>b.addEventListener("click",()=>renderModule(b.dataset.module)));
document.addEventListener("click",e=>{const b=e.target.closest("[data-go]");if(b)renderModule(b.dataset.go);});
function openAuth(){if(!supabaseReady){$("#authMessage").className="message";$("#authMessage").textContent="Set SUPABASE_URL and SUPABASE_ANON_KEY in app.js first. Guest mode is available now.";$("#authDialog").showModal();return;}authMode="signin";updateAuthForm();$("#authDialog").showModal();}
function updateAuthForm(){$("#authTitle").textContent=authMode==="signin"?"Welcome back":"Create your account";$("#authDescription").textContent=authMode==="signin"?"Sign in to sync your saved analyses.":"Create an account to save analyses across devices.";$("#authSubmit").textContent=authMode==="signin"?"Sign in":"Create account";$("#toggleAuth").textContent=authMode==="signin"?"Need an account? Sign up":"Already have an account? Sign in";$("#authMessage").textContent="";}
$("#authButton").onclick=()=>currentUser?signOut():openAuth();$("#closeAuth").onclick=()=>$("#authDialog").close();$("#toggleAuth").onclick=()=>{authMode=authMode==="signin"?"signup":"signin";updateAuthForm();};
$("#authForm").addEventListener("submit",async e=>{e.preventDefault();if(!db)return;const email=$("#authEmail").value,password=$("#authPassword").value;$("#authSubmit").disabled=true;$("#authMessage").textContent="Working…";try{const res=authMode==="signin"?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});if(res.error)throw res.error;if(authMode==="signup"&&!res.data.session){$("#authMessage").className="message success";$("#authMessage").textContent="Account created. Check your email if confirmation is enabled, then sign in.";}else{$("#authDialog").close();await refreshSession();}}catch(err){$("#authMessage").className="message";$("#authMessage").textContent=err.message||"Authentication failed.";}finally{$("#authSubmit").disabled=false;}});
async function refreshSession(){if(!db)return;const {data}=await db.auth.getSession();currentUser=data.session?.user||null;updateAccount();db.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;updateAccount();});}
function updateAccount(){$("#userLabel").textContent=currentUser?(currentUser.email||"Signed in"):"Guest mode";$("#authButton").textContent=currentUser?"Sign out":"Sign in";$("#connectionText").textContent=supabaseReady?(currentUser?"Supabase connected":"Supabase ready"):"Local workspace";}
async function signOut(){if(db)await db.auth.signOut();currentUser=null;updateAccount();}
async function saveCurrent(title){const msg=$("#saveMessage");if(!latestAnalysis){msg.textContent="Run an analysis first.";return;}if(!currentUser||!db){msg.textContent="Guest analyses are not uploaded. Sign in after connecting Supabase to save to your account.";return;}msg.textContent="Saving…";try{const {error}=await db.from("saved_analyses").insert({user_id:currentUser.id,title,analysis:latestAnalysis});if(error)throw error;msg.className="message success";msg.textContent="Analysis saved to your Supabase account.";}catch(e){msg.className="message";msg.textContent=`Could not save: ${e.message}. Confirm the SQL setup and Row Level Security policies.`;}}
if(supabaseReady){refreshSession();}else updateAccount();
renderHome();
